### ISSUE TITLE
Any way to make it work as advertised?

### ISSUE THREAD

**Issue by rubyconvict** [kvokka/pp_sql#1]
> User.limit(1).to_sql
 => "SELECT\n    `users`. *\n  FROM\n    `users` LIMIT 1"

**Comment by kvokka** [comment]
As it was written in readme, you should use puts in front of the command, like `puts User.limit(1).to_sql`

Or you may update gem to version 0.1.1 and use `pp_sql` method, which may be more handy.

Enjoy :)
