### ISSUE TITLE
Undefined method `one?' for 1:Integer

### ISSUE THREAD

**Issue by wa0x6e** [kvokka/pp_sql#6]
Hi,

I tried using this gem, and it does pretty format the SQL, but returns the following warning after each query

```
Could not log "sql.active_record" event. NoMethodError: undefined method `one?' for 1:Integer
```

I'm using Rails 5, on Ruby 2.4

**Comment by kvokka** [comment]
Really strange, but try to update to 0.2.3 version, it will be fixed
